Document: libyuv
Title: Debian libyuv Manual
Author: <insert document author here>
Abstract: This manual describes what libyuv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libyuv/libyuv.sgml.gz

Format: postscript
Files: /usr/share/doc/libyuv/libyuv.ps.gz

Format: text
Files: /usr/share/doc/libyuv/libyuv.text.gz

Format: HTML
Index: /usr/share/doc/libyuv/html/index.html
Files: /usr/share/doc/libyuv/html/*.html
